spring.application.name=billing-backend
# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/nexbill_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port Setup
server.port=8080