spring.application.name=billing-backend
# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/nexbill_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port Setup
server.port=8080
# JWT Security Key Configurations Base Settings
<<<<<<< HEAD
# 64-character (256-bit) Base64 encoded key for HS256
application.security.jwt.secret-key=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
application.security.jwt.expiration=86400000

#application.security.jwt.secret-key=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
#application.security.jwt.expiration=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dveininnovations.projects@gmail.com
spring.mail.password=uwil gqsr rwcg wecs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
>>>>>>> 5b2a7815c86071a4f389928e5988ff97f0162186
