spring.application.name=billing-backend
# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/nexbill_db
spring.datasource.username=postgres
spring.datasource.password=navin2065
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port Setup
server.port=8080
# JWT Security Key Configurations Base Settings
application.security.jwt.secret-key=9a4f2c8d3e1b7f6a5c4d3b2a1e0f9b8c7a6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1
application.security.jwt.expiration=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dveininnovations.projects@gmail.com
spring.mail.password=uwil gqsr rwcg wecs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true